image_proc/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('identify_image/', views.identify_image, name='identify_image'),
    path('success/', views.success, name='success'),
]

simple_proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('image_proc/', include('image_proc.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

image_proc/models.py
from django.db import models
import os
from simple_proj import settings

def file_name(instance, filename):
    imgname = 'image.jpg'
    fullname = os.path.join(settings.MEDIA_ROOT, imgname)
    if os.path.exists(fullname):
        os.remove(fullname)
    return imgname
# Create your models here.
class Image(models.Model): 
    image = models.ImageField(upload_to=file_name) 

image_proc/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from imageai.Detection import ObjectDetection
from django.template import loader
from django import forms
from django.core.files.storage import FileSystemStorage
from .models import *
import os


fs = FileSystemStorage(location = 'media/files/')

# Create your views here.
def index(request):
    return HttpResponse("Image Processing App!!")

class ImageForm(forms.ModelForm): 
  
    class Meta: 
        model = Image 
        fields = ['image'] 

def identify_image(request):
    if request.method == 'GET':
        form = ImageForm()
    elif request.method == 'POST':
        form = ImageForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
        return redirect('success')
    return render(request, 'image_proc/identify_image.html', {'form': form})

def success(request): 
    execution_path = os.getcwd()
    detector = ObjectDetection()
    detector.setModelTypeAsRetinaNet()
    detector.setModelPath( os.path.join(execution_path , "resnet50_coco_best_v2.0.1.h5"))
    detector.loadModel()
    detections = detector.detectObjectsFromImage(input_image=os.path.join(execution_path , "media/image.jpg"))
    string = ""
    for eachObject in detections:
        string += eachObject["name"] + "\n"
    return HttpResponse('successfuly uploaded!! Objects detected are: ' + string) 

image_proc/templates/image_proc/identify_image.html
<form action="{% url identify_image %}" method="post" enctype="multipart/form-data">{% csrf_token %}
    <p>
        <input id="id_image" type="file" class="" name="image">
    </p>
    <input type="submit" value="Submit" />
</form>

templates/image_proc/identify_image.html
<!DOCTYPE html> 
<html lang="en"> 
<head> 
    <meta charset="UTF-8"> 
    <title>Image</title> 
</head> 
<body> 
    <form method = "post" enctype="multipart/form-data"> 
        {% csrf_token %} 
        {{ form.as_p }} 
        <button type="submit">Upload</button> 
    </form> 
</body> 
</html> 